package org.sinytra.connector.infinity.inventory;

import java.util.Set;

/** Exact audited declarations, never prefixes. Sources/pins are documented in admission-inventory.md. */
final class AuditedInfrastructureIds {
    private AuditedInfrastructureIds() {}
    static final Set<String> UNSUPPORTED_QSL = Set.of(
        "quilt_biome",
        "quilt_block_content_registry",
        "quilt_block_entity",
        "quilt_block_extensions",
        "quilt_chat",
        "quilt_client_command",
        "quilt_command",
        "quilt_crash_info",
        "quilt_data_callback",
        "quilt_dimension",
        "quilt_entity_events",
        "quilt_entity_extensions",
        "quilt_entity_multipart",
        "quilt_entity_rendering",
        "quilt_item_content_registry",
        "quilt_item_extensions",
        "quilt_item_setting",
        "quilt_networking",
        "quilt_recipe",
        "quilt_registry",
        "quilt_registry_entry_attachment",
        "quilt_resource_loader",
        "quilt_screen",
        "quilt_status_effect",
        "quilt_surface_rule",
        "quilt_tags",
        "quilt_testing",
        "quilt_tooltip");
    static final Set<String> FFAPI_MODULES = Set.of(
        "fabric_api_base",
        "fabric_api_lookup_api_v1",
        "fabric_biome_api_v1",
        "fabric_block_api_v1",
        "fabric_block_view_api_v2",
        "fabric_blockrenderlayer_v1",
        "fabric_client_tags_api_v1",
        "fabric_command_api_v2",
        "fabric_content_registries_v0",
        "fabric_convention_tags_v1",
        "fabric_convention_tags_v2",
        "fabric_data_attachment_api_v1",
        "fabric_data_generation_api_v1",
        "fabric_entity_events_v1",
        "fabric_events_interaction_v0",
        "fabric_game_rule_api_v1",
        "fabric_gametest_api_v1",
        "fabric_item_api_v1",
        "fabric_item_group_api_v1",
        "fabric_key_binding_api_v1",
        "fabric_lifecycle_events_v1",
        "fabric_loot_api_v2",
        "fabric_loot_api_v3",
        "fabric_message_api_v1",
        "fabric_model_loading_api_v1",
        "fabric_networking_api_v1",
        "fabric_object_builder_api_v1",
        "fabric_particles_v1",
        "fabric_recipe_api_v1",
        "fabric_registry_sync_v0",
        "fabric_renderer_api_v1",
        "fabric_renderer_indigo",
        "fabric_rendering_data_attachment_v1",
        "fabric_rendering_fluids_v1",
        "fabric_rendering_v1",
        "fabric_resource_conditions_api_v1",
        "fabric_resource_loader_v0",
        "fabric_screen_api_v1",
        "fabric_screen_handler_api_v1",
        "fabric_sound_api_v1",
        "fabric_transfer_api_v1",
        "fabric_transitive_access_wideners_v1");
}
