modLoader="javafml"
loaderVersion="[52,53)"
license="MIT"

[[mods]]
modId="unified_forge_probe"
version="0.1.0"
displayName="Unified Forge Native ABI Probe"
description='''Project-owned Forge-only lifecycle, registry, tick and persistence control.'''

[[dependencies.unified_forge_probe]]
modId="forge"
mandatory=true
versionRange="[52.1.0,52.2)"
ordering="NONE"
side="BOTH"

[[dependencies.unified_forge_probe]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
